spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitcheck
      database: aiactivityfitcheck

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
    port: 8082

