spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitcheck_microservice_user
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect